version: '3.8'
services:
  cineproject-api:
    build:
      context: .
      dockerfile: CineProject.API/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - cineproject-consumer

  cineproject-consumer:
    build:
      context: .
      dockerfile: CineProject.Consumer/Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID=TESTE
      - AWS_SECRET_ACCESS_KEY=TESTEACCESS
      - ASPNETCORE_ENVIRONMENT=Production
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - TMPDIR=/new_tmp_directory
    volumes:
      - "./localstack_data:/new_tmp_directory"

volumes:
  mongo_data:
  localstack_data:
